void prompt();
char *get_path();
void set_path(char *Input);
void change_directory(char* dir);
void print_history(char *histarr[20], int commandIndex);
int check_hist_exec(char *input) ;
int check_hist_exec_minus(char *input);
int str_exec_num(char* input1,int index , char* histarr[]);
int str_exec_num_minus(char* input1, int index);
int add_history(char *histarr[20], int commandIndex, char* command);
void tokenise(char* tokensarr[],char* line);
int getHistFromFile(char *histarr[20],char *origDir);
void sendHistToFile(int commandindex, char *histarr[20], char* origdir);
void addToAlias(char* alias[10][2],char* name,char* command);
void removeAlias(char* alias[10][2],char* name);
void printAlias(char* alias[10][2]);
void saveAliasToFile(char* alias[10][2],char* origdir);
void loadAliasFile(char* alias[10][2], char* origdir);
